// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// langMH
List langMH(NumericVector x, Function fn, Function gr, NumericMatrix prCov, NumericMatrix prChol, int ndraws);
RcppExport SEXP ads_langMH(SEXP xSEXP, SEXP fnSEXP, SEXP grSEXP, SEXP prCovSEXP, SEXP prCholSEXP, SEXP ndrawsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Function >::type fn(fnSEXP);
    Rcpp::traits::input_parameter< Function >::type gr(grSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type prCov(prCovSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type prChol(prCholSEXP);
    Rcpp::traits::input_parameter< int >::type ndraws(ndrawsSEXP);
    __result = Rcpp::wrap(langMH(x, fn, gr, prCov, prChol, ndraws));
    return __result;
END_RCPP
}
