# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title dMVN
#' @name dMVN
#' @param X_ matrix
#' @param mu_ vector
#' @param L_ lower chol of cov or prec matrix
#' @param isPrec covariance or precision matrix?
#' @return Numeric vector
#' @export
dMVN <- function(X_, mu_, L_, isPrec) {
    .Call('ads_dMVN', PACKAGE = 'ads', X_, mu_, L_, isPrec)
}

#' @title rMVN
#' @name rMVN
#' @param N integer, number of draws
#' @param mu_ mean vector
#' @param L_ lower chol of cov or prec matrix
#' @param isPrec covariance or precision matrix?
#' @return Numeric matrix
#' @export
rMVN <- function(N, mu_, L_, isPrec) {
    .Call('ads_rMVN', PACKAGE = 'ads', N, mu_, L_, isPrec)
}

#' @title dMVT
#' @param X_ matrix
#' @param mu_ vector
#' @param L_ lower chol of cov or prec matrix
#' @param v degrees of freedom (must be >=3)
#' @param isInv is scale matrix an inverse covariance?
#' @return Numeric vector
#' @export
dMVT <- function(X_, mu_, L_, v, isInv) {
    .Call('ads_dMVT', PACKAGE = 'ads', X_, mu_, L_, v, isInv)
}

#' @title rMVT
#' @param N integer, number of draws
#' @param mu_ mean vector
#' @param L_ lower chol of cov or prec matrix
#' @param v degrees of freedom (must be >=3)
#' @param isInv is scale matrix an inverse?
#' @return Numeric matrix
#' @export
rMVT <- function(N, mu_, L_, v, isInv) {
    .Call('ads_rMVT', PACKAGE = 'ads', N, mu_, L_, v, isInv)
}

