# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title dMVN
#' @param X_ matrix
#' @param mu_ matrix
#' @param G_ full covariance or precision matrix
#' @param isPrec covariance or precision matrix?
#' @return Numeric vector
#' @export
dMVN <- function(X_, mu_, L_, isPrec) {
    .Call('ads_dMVN', PACKAGE = 'ads', X_, mu_, L_, isPrec)
}

