# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title dMVN
#' @param X_ matrix
#' @param mu_ vector
#' @param L_ lower chol of cov or prec matrix
#' @param isPrec covariance or precision matrix?
#' @return Numeric vector
#' @export
dMVN <- function(X_, mu_, L_, isPrec) {
    .Call('ads_dMVN', PACKAGE = 'ads', X_, mu_, L_, isPrec)
}

#' @title rMVN
#' @param N integer, number of draws
#' @param mu_ mean vector
#' @param L_ lower chol of cov or prec matrix
#' @param isPrec covariance or precision matrix?
#' @return Numeric matrix
#' @export
rMVN <- function(N, mu_, L_, isPrec) {
    .Call('ads_rMVN', PACKAGE = 'ads', N, mu_, L_, isPrec)
}

